"use strict";
var _a, _b;
Object.defineProperty(exports, "__esModule", { value: true });
exports.ID_CHANNEL_BOT_ACTIVITY = exports.ID_GUILD_MAIN = exports.TOKEN_BOT_DISCORD = void 0;
const dotenv_1 = require("dotenv");
const path_1 = require("path");
(0, dotenv_1.config)({ path: (0, path_1.join)(__dirname, '..', '.env') });
exports.TOKEN_BOT_DISCORD = process.env.TOKEN_BOT_DISCORD;
exports.ID_GUILD_MAIN = (_a = process.env.ID_GUILD_MAIN) !== null && _a !== void 0 ? _a : 'Here default ID_GUILD_MAIN';
exports.ID_CHANNEL_BOT_ACTIVITY = (_b = process.env.ID_CHANNEL_BOT_ACTIVITY) !== null && _b !== void 0 ? _b : 'Here default ID_CHANNEL_BOT_ACTIVITY';
